# Generated by Django 5.2.5 on 2025-09-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_itemcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcomment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='playground.item'),
        ),
    ]
